server:
  port: 8080
spring:
  application:
    name: eureka-service

security:
  user:
    name: admin
    password: 123456


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    ip-address: 192.168.0.233